# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "About"
  url = "#about"
  weight = 10
 
 [[main]]
    name = "CV"
    url = "media/cv.pdf"
    weight = 20

[[main]]
  name = "RSS"
  url = "#rss"
  weight=25

[[main]]
  name = "Blog"
  url = "#projects"
  weight = 30

[[main]]
  name = "Publications"
  url = "#posts"
  weight = 40