intro = """\
        Hi! I'm Christopher, a fourth-year PhD student in the [Galloway Lab](https://gallowaylab.mit.edu). \
        You can find my publications and posts below. Check out the [About](/about) page \
        for contact information, Github, ORCID, and more. \
        """
privacy_policy = """\
                 This site uses a self-hosted [Plausible](https://plausible.io/) instance \
                 for visitor counting in a cookie-free, open-source, and privacy-preserving manner.
                 """